<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apib</string>
	</array>
	<key>name</key>
	<string>Apiary Blueprint</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.host.apib</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^HOST:(.*)</string>
			<key>name</key>
			<string>keyword.host.apib</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.apiname.apib</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^--- (.+)---</string>
			<key>name</key>
			<string>meta.apiname.apib</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^---</string>
			<key>end</key>
			<string>^---</string>
			<key>name</key>
			<string>comment.apidescription.apib</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=^--)</string>
			<key>end</key>
			<string>(?=^GET|^POST|^PUT|^DELETE|^OPTIONS|^PATCH|^PROPPATCH|^LOCK|^UNLOCK|^COPY|^MOVE|^MKCOL)</string>
			<key>name</key>
			<string>meta.apidescription.apib</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^-- (.*)--</string>
					<key>name</key>
					<string>entity.name.class.section.apib</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>comment.apidescription.apib</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(GET|POST|PUT|DELETE|OPTIONS|PATCH|PROPPATCH|LOCK|UNLOCK|COPY|MOVE|MKCOL)\b(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.resource.apib</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.resource.apib</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^GET|^POST|^PUT|^DELETE|^OPTIONS|^PATCH|^PROPPATCH|^LOCK|^UNLOCK|^COPY|^MOVE|^MKCOL|^--)</string>
			<key>name</key>
			<string>meta.resourcedescription.apib</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=^$^$)</string>
					<key>end</key>
					<string>(?=^GET|^POST|^PUT|^DELETE|^OPTIONS|^PATCH|^PROPPATCH|^LOCK|^UNLOCK|^COPY|^MOVE|^MKCOL|^--)</string>
					<key>name</key>
					<string>comment.resourcedescription.apib</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.integer.httpstatus.apib</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.httpheader.name.apib</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.httpheader.apib</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.httpheader.value.apib</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[&gt;&lt;](?:(?: (\d+))|(?: ([a-zA-Z0-9\-]+)(:)(.+)))?</string>
					<key>name</key>
					<string>storage.inout.apib</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+{5}</string>
					<key>name</key>
					<string>punctuation.responseseparator.apib</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.json</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.apib</string>
	<key>uuid</key>
	<string>66b295dc-333a-11e2-9c92-1093e9011416</string>
</dict>
</plist>
