<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>apib</string>
	</array>
	<key>name</key>
	<string>Apiary Blueprint</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.value.host.apib</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^HOST:(.*)</string>
			<key>name</key>
			<string>keyword.host.apib</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.apiname.apib</string>
				</dict>
			</dict>
			<key>match</key>
			<string>--- (.+)---</string>
			<key>name</key>
			<string>meta.markup.heading.1.apib</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>---</string>
			<key>end</key>
			<string>---</string>
			<key>name</key>
			<string>comment.block.apidescription.apib</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.apib</string>
	<key>uuid</key>
	<string>66b295dc-333a-11e2-9c92-1093e9011416</string>
</dict>
</plist>
